#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ]

### CREATE DIRECTORIES ###
mkdir -p "$logdir" "$datadir"
chown www-data:www-data "$logdir" "$datadir"

### INSTALL THIS SYSTEM ###
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown www-data:www-data "$appdir" -R

### RENAME FETCH CGI ###
cd  "$appdir"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)
[ -e "/home/todayokgo/rnd" ] && rnd=$(cat /home/todayokgo/rnd )
mv "fetch" "fetch_$rnd.cgi"

### PULL ARTICLE REPO ###
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"
chown www-data:www-data "$contentsdir" -R

echo "call fetch_$rnd.cgi from GitHub"
